### ISSUE TITLE
current lock file requires poetry version => 1.1.12

### ISSUE THREAD

**Issue by iannesbitt** [DataONEorg/mnlite#20]
Either update lock file or add to documentation that the current lock file requires `poetry==1.1.12` instead of current poetry version.

**Comment by mbjones** [comment]
Poetry lock files are meant to temporarily freeze a repo so that people can reliably install. As the devs, we should forward migrate dependencies whenever possible. From a high level, there shouldn't be a reason we need to keep the package on an old poetry version.

**Comment by iannesbitt** [comment]
Closing (resolution is to delete and regenerate the lock file in a higher version of `poetry`).
