### ISSUE TITLE
OpenTopography's records do not resolve an `identifier`

### ISSUE THREAD

**Issue by iannesbitt** [DataONEorg/mnlite#31]
Every OpenTopography record raises `JSON-LD no ids, not a Dataset:` because there is no `identifier` field returned when `mnlite.sonormalizepipeline.SoscanNormalizePipeline.process_item()` attempts to find `ids`. The schema.org records look valid even to the validator tools. It looks like the error gets introduced ~when `sonormal.sosoNormalize` calls `sonormal.addSchemaOrgListContainer` which uses `pyld.jsonld.expand`~ during [`sonormal.normalize.frameSODataset`](https://github.com/DataONEorg/sonormal/blob/develop/sonormal/normalize.py#L115-L126), leaving only the following to be returned in the `ids` variable (empty `identifier`):
```python
[{'@id': ['https://portal.opentopography.org/lidarDataset?opentopoID=OTLAS.042012.26911.5'], 'url': ['https://doi.org/10.5069/G9TB14TM'], 'identifier': []}]
```

Here is the dataset `identifier` field before and after normalization (i.e. what [`sonormal.normalize._getIdentifiers`](https://github.com/DataONEorg/sonormal/blob/develop/sonormal/normalize.py#L44-L60) looks at to get `ids`.

Before expansion:
```python
            'identifier': {'@id': 'https://portal.opentopography.org/lidarDataset?opentopoID=OTLAS.042012.26911.5',
                           '@type': 'PropertyValue',
                           'propertyID': 'opentopoID',
                           'value': 'OTLAS.042012.26911.5'},
```

After expansion but before compaction:
```python
    "https://schema.org/identifier": [
      {"@id": "https://portal.opentopography.org/lidarDataset?opentopoID=OTLAS.042012.26911.5",
        "@type": ["https://schema.org/PropertyValue"],
        "https://schema.org/propertyID": [{"@value": "opentopoID"}],
        "https://schema.org/value": [{"@value": "OTLAS.042012.26911.5"}]
      }],
```

After initial compaction:
```python
  "identifier": {
    "@id": "https://portal.opentopography.org/lidarDataset?opentopoID=OTLAS.042012.26911.5",
    "@type": "PropertyValue",
    "propertyID": "opentopoID",
    "value": "OTLAS.042012.26911.5"
  },
```

after `sonormal.addSchemaOrgListContainer`:
```python
    "http://schema.org/identifier": [
      {"@list": [{
            "@id": "https://portal.opentopography.org/lidarDataset?opentopoID=OTLAS.042012.26911.5",
            "@type": ["http://schema.org/PropertyValue"],
            "http://schema.org/propertyID": [{"@value": "opentopoID"}],
            "http://schema.org/value": [{"@value": "OTLAS.042012.26911.5"}]
      }]}],
```

after `sonormal.normalize.frameSODataset`:
```python
    "http://schema.org/identifier": [{"@list":
          [{"@id": "https://portal.opentopography.org/lidarDataset?opentopoID=OTLAS.042012.26911.5"}]
    }],
```

Potential solutions:
1. Change [`sonormal.normalize._getIdentifiers`](https://github.com/DataONEorg/sonormal/blob/develop/sonormal/normalize.py#L44-L60) to include the `@id` tag in its search (currently only gets `@value`) <- quick fix — [I tested this and it's working](https://so.test.dataone.org/mnTestOPENTOPOGRAPHY/v2/), but it uses the whole URL as SID which isn't ideal
2. Change either framing ([`pyld.jsonld.frame`](https://github.com/datadavev/pyld/blob/ddv-2.1.0/lib/pyld/jsonld.py#L188-L214)) or expansion ([`pyld.jsonld.expand`](https://github.com/datadavev/pyld/blob/ddv-2.1.0/lib/pyld/jsonld.py#L145-L163)) (or [the frame](https://github.com/DataONEorg/sonormal/blob/develop/sonormal/normalize.py#L118C35-L118C60) provided by [`sonormal.normalize.frameSODataset`](https://github.com/DataONEorg/sonormal/blob/develop/sonormal/normalize.py#L115-L126)) such that the output keeps `'value': 'OTLAS.042012.26911.5'` in the identifier list
3. Contact OT to have them change their SO template to something normalization can handle

Perhaps @datadavev has experience with this issue or something similar?

**Comment by iannesbitt** [comment]
Edit: I got my jsonld variables mixed up initially. I posted the correct json-ld outputs and correct function attribution (`sonormal.normalize.frameSODataset`) in the post above.

**Comment by iannesbitt** [comment]
The error happens in `pyld.jsonld.frame()` but I don't know if it has to do with the contents of `sonormal.SO_DATASET_FRAME` or due to an issue within the function itself.

Another possibility is setting `require_identifier = False` in sonormalizepipeline, but I'm not sure what would serve as SID in that case...

It's a silly problem to have because there are several places where `http://schema.org/identifier` value is set in the graph...just not in the place where `sonormal.normalize.getDatasetsIdentifiers` is looking. For example:
```python
>>> _framed[0]["http://schema.org/includedInDataCatalog"][0]["http://schema.org/identifier"][0]["@list"][0]["http://schema.org/value"][0]["@value"]
'10.5069/G9TB14TM'
```
or even
```python
>>> sosodoc[0]["http://schema.org/identifier"][0]["@list"][0]["http://schema.org/value"][0]["@value"]
'OTLAS.042012.26911.5'
```

**Comment by iannesbitt** [comment]
I have isolated this issue to [framing](https://json-ld.org/playground/#startTab=tab-framed&json-ld=%7B%22%40id%22%3A%22https%3A%2F%2Fportal.opentopography.org%2FlidarDataset%3FopentopoID%3DOTLAS.042012.26911.5%22%2C%22%40type%22%3A%5B%22http%3A%2F%2Fschema.org%2FDataset%22%5D%2C%22http%3A%2F%2Fschema.org%2FadditionalType%22%3A%5B%7B%22%40value%22%3A%22geolink%3ADataset%22%7D%2C%7B%22%40value%22%3A%22vivo%3ADataset%22%7D%5D%2C%22http%3A%2F%2Fschema.org%2FalternateName%22%3A%5B%7B%22%40value%22%3A%22ILC04_Emerald%22%7D%5D%2C%22http%3A%2F%2Fschema.org%2Fcitation%22%3A%5B%7B%22%40value%22%3A%22Idaho%20LiDAR%20Consortium%20(ILC)%3A%20Emerald%20Creek.%20Distributed%20by%20OpenTopography.%20https%3A%2F%2Fdoi.org%2F10.5069%2FG9TB14TM%20.%20Accessed%3A%202023-09-14%22%7D%5D%2C%22http%3A%2F%2Fschema.org%2Fcontributor%22%3A%5B%7B%22%40type%22%3A%5B%22http%3A%2F%2Fschema.org%2FOrganization%22%5D%2C%22http%3A%2F%2Fschema.org%2Fname%22%3A%5B%7B%22%40value%22%3A%22Spectrum%20Mapping%20LLC%22%7D%5D%7D%2C%7B%22%40type%22%3A%5B%22http%3A%2F%2Fschema.org%2FOrganization%22%5D%2C%22http%3A%2F%2Fschema.org%2Fname%22%3A%5B%7B%22%40value%22%3A%22Idaho%20LiDAR%20Consortium%22%7D%5D%2C%22http%3A%2F%2Fschema.org%2Furl%22%3A%5B%7B%22%40value%22%3A%22https%3A%2F%2Fwww.idaholidar.org%2F%22%7D%5D%7D%5D%2C%22http%3A%2F%2Fschema.org%2Fdescription%22%3A%5B%7B%22%40list%22%3A%5B%7B%22%40value%22%3A%22The%20lidar%20survey%20was%20conducted%20by%20vendor%20Spectrum%20Mapping%20LCC%2C%20a%20Lidar%20company.%20Lidar%20instrument%20Datis%20II%20sensor%20was%20flown%20over%20the%20period%20of%2010%20and%2012%20July%202004.%20The%20data%20were%20delivered%20in%20ASCII%20format%20(files%20separated%20by%20vegetation%20points%20and%20ground%20points)%20with%20information%20on%20X%2C%20Y%2C%20elevation%2C%20Return%20number%2C%20RGB%20and%20scan%20angle.%20The%20primary%20goal%20of%20the%20study%20is%20to%20provide%20operational%20implementation%20of%20Lidar%20technology%20in%20support%20of%20project%20level%20planning.%20The%20proposed%20applications%20of%20Lidar%20in%20support%20of%20planning%20are%3A%20vegetation%20structural%20modeling%2C%20erosion%20modeling%2C%20fuels%2C%20transportation%20planning%2C%20timber%20system%20planning%2C%20wildlife%20habitat%20modeling%2C%20and%20stream%20quality.%20The%20Rocky%20Mountain%20Research%20Station%20will%20provide%20the%20development%20of%20peer-reviewed%20forest%20structural%20metrics%20and%20technical%20support%20in%20implementation%20of%20Lidar%20technology.%20The%20technical%20specifications%20have%20been%20defined%20to%20specifically%20support%20vegetation%20modeling%20using%20Lidar%20data.%20The%20project%20area%20consists%20of%20one%20contiguous%20blocks%20totaling%2013234%20hectares%20in%20str(E)merald%20Creek%2C%20St.%20Joe%20National%20Forest%2C%20Idaho.%20The%20project%20area%20consists%20of%20moderately%20variable%20topographic%20configurations%20with%20diverse%20vegetation%20components.%22%7D%5D%7D%5D%2C%22http%3A%2F%2Fschema.org%2FencodingFormat%22%3A%5B%7B%22%40value%22%3A%22application%2Foctet-stream%3Btype%3DASPRS-LAS%22%7D%5D%2C%22http%3A%2F%2Fschema.org%2FfileFormat%22%3A%5B%7B%22%40value%22%3A%22Point%20Cloud%20Data%22%7D%5D%2C%22http%3A%2F%2Fschema.org%2Ffunder%22%3A%5B%7B%22%40type%22%3A%5B%22http%3A%2F%2Fschema.org%2FOrganization%22%5D%2C%22http%3A%2F%2Fschema.org%2Fname%22%3A%5B%7B%22%40value%22%3A%22United%20States%20Forest%20Service%20Rocky%20Mountain%20Research%20Station%22%7D%5D%2C%22http%3A%2F%2Fschema.org%2Furl%22%3A%5B%7B%22%40value%22%3A%22https%3A%2F%2Fwww.fs.fed.us%2Frmrs%2F%22%7D%5D%7D%5D%2C%22http%3A%2F%2Fschema.org%2Fidentifier%22%3A%5B%7B%22%40list%22%3A%5B%7B%22%40id%22%3A%22https%3A%2F%2Fportal.opentopography.org%2FlidarDataset%3FopentopoID%3DOTLAS.042012.26911.5%22%2C%22%40type%22%3A%5B%22http%3A%2F%2Fschema.org%2FPropertyValue%22%5D%2C%22http%3A%2F%2Fschema.org%2FpropertyID%22%3A%5B%7B%22%40value%22%3A%22opentopoID%22%7D%5D%2C%22http%3A%2F%2Fschema.org%2Fvalue%22%3A%5B%7B%22%40value%22%3A%22OTLAS.042012.26911.5%22%7D%5D%7D%5D%7D%5D%2C%22http%3A%2F%2Fschema.org%2FincludedInDataCatalog%22%3A%5B%7B%22%40type%22%3A%5B%22http%3A%2F%2Fschema.org%2FDataCatalog%22%5D%2C%22http%3A%2F%2Fschema.org%2Fidentifier%22%3A%5B%7B%22%40list%22%3A%5B%7B%22%40id%22%3A%22https%3A%2F%2Fdoi.org%2F10.5069%2FG9TB14TM%22%2C%22%40type%22%3A%5B%22http%3A%2F%2Fschema.org%2FPropertyValue%22%5D%2C%22http%3A%2F%2Fschema.org%2FadditionalType%22%3A%5B%7B%22%40value%22%3A%22geolink%3AIdentifier%22%7D%2C%7B%22%40value%22%3A%22datacite%3AIdentifier%22%7D%5D%2C%22http%3A%2F%2Fschema.org%2FpropertyID%22%3A%5B%7B%22%40value%22%3A%22datacite%3Adoi%22%7D%5D%2C%22http%3A%2F%2Fschema.org%2Furl%22%3A%5B%7B%22%40value%22%3A%22https%3A%2F%2Fdoi.org%2F10.5069%2FG9TB14TM%22%7D%5D%2C%22http%3A%2F%2Fschema.org%2Fvalue%22%3A%5B%7B%22%40value%22%3A%2210.5069%2FG9TB14TM%22%7D%5D%7D%5D%7D%5D%2C%22http%3A%2F%2Fschema.org%2Fname%22%3A%5B%7B%22%40value%22%3A%22Idaho%20LiDAR%20Consortium%20(ILC)%3A%20Emerald%20Creek%22%7D%5D%2C%22http%3A%2F%2Fschema.org%2Furl%22%3A%5B%7B%22%40value%22%3A%22https%3A%2F%2Fportal.opentopography.org%2FdatasetMetadata%3FotCollectionID%3DOT.042012.26911.5%22%7D%5D%7D%5D%2C%22http%3A%2F%2Fschema.org%2FisAccessibleForFree%22%3A%5B%7B%22%40value%22%3Atrue%7D%5D%2C%22http%3A%2F%2Fschema.org%2Fkeywords%22%3A%5B%7B%22%40value%22%3A%22Idaho%2C%20lidar%22%7D%5D%2C%22http%3A%2F%2Fschema.org%2FlocationCreated%22%3A%5B%7B%22%40value%22%3A%22%22%7D%5D%2C%22http%3A%2F%2Fschema.org%2Fname%22%3A%5B%7B%22%40value%22%3A%22Idaho%20Lidar%20Consortium%20(ILC)%3A%20Emerald%20Creek%22%7D%5D%2C%22http%3A%2F%2Fschema.org%2Fpublisher%22%3A%5B%7B%22%40type%22%3A%5B%22http%3A%2F%2Fschema.org%2FOrganization%22%5D%2C%22http%3A%2F%2Fschema.org%2FadditionalType%22%3A%5B%7B%22%40value%22%3A%22geolink%3AOrganization%22%7D%5D%2C%22http%3A%2F%2Fschema.org%2Faward%22%3A%5B%7B%22%40value%22%3A%22National%20Science%20Foundation%20under%20Award%20Numbers%20EAR-1948997%2C%201948994%20%26%201948857%22%7D%5D%2C%22http%3A%2F%2Fschema.org%2Femail%22%3A%5B%7B%22%40value%22%3A%22info%40opentopography.org%22%7D%5D%2C%22http%3A%2F%2Fschema.org%2FlegalName%22%3A%5B%7B%22%40value%22%3A%22OpenTopography%22%7D%5D%2C%22http%3A%2F%2Fschema.org%2Fname%22%3A%5B%7B%22%40value%22%3A%22OpenTopography%22%7D%5D%2C%22http%3A%2F%2Fschema.org%2Flogo%22%3A%5B%7B%22%40value%22%3A%22http%3A%2F%2Fwww.opentopography.org%2Fsites%2Fopentopography.org%2Ffiles%2Fot_transp_logo.png%22%7D%5D%2C%22http%3A%2F%2Fschema.org%2Furl%22%3A%5B%7B%22%40value%22%3A%22https%3A%2F%2Fopentopography.org%22%7D%5D%7D%5D%2C%22http%3A%2F%2Fschema.org%2FdateCreated%22%3A%5B%7B%22%40value%22%3A%222012-05-04%2014%3A07%3A47.074058%22%7D%5D%2C%22http%3A%2F%2Fschema.org%2Flicense%22%3A%5B%7B%22%40value%22%3A%22Not-Provided%22%7D%5D%2C%22http%3A%2F%2Fschema.org%2FsameAs%22%3A%5B%7B%22%40value%22%3A%22https%3A%2F%2Fportal.opentopography.org%2FdatasetMetadata%3FotCollectionID%3DOT.042012.26911.5%22%7D%5D%2C%22http%3A%2F%2Fschema.org%2Furl%22%3A%5B%7B%22%40value%22%3A%22https%3A%2F%2Fdoi.org%2F10.5069%2FG9TB14TM%22%7D%5D%2C%22http%3A%2F%2Fschema.org%2FspatialCoverage%22%3A%5B%7B%22%40type%22%3A%5B%22http%3A%2F%2Fschema.org%2FPlace%22%5D%2C%22http%3A%2F%2Fschema.org%2FadditionalProperty%22%3A%5B%7B%22%40type%22%3A%5B%22http%3A%2F%2Fschema.org%2FPropertyValue%22%5D%2C%22http%3A%2F%2Fschema.org%2FadditionalType%22%3A%5B%7B%22%40value%22%3A%22CoordinatesSystem%22%7D%5D%2C%22http%3A%2F%2Fschema.org%2Fname%22%3A%5B%7B%22%40value%22%3A%22Horizontal%20Coordinates%22%7D%5D%2C%22http%3A%2F%2Fschema.org%2Fvalue%22%3A%5B%7B%22%40value%22%3A%22UTM%20Zone%2011N%20NAD83%20%5BEPSG%3A%2026911%5D%22%7D%5D%7D%2C%7B%22%40type%22%3A%5B%22http%3A%2F%2Fschema.org%2FPropertyValue%22%5D%2C%22http%3A%2F%2Fschema.org%2FadditionalType%22%3A%5B%7B%22%40value%22%3A%22CoordinatesSystem%22%7D%5D%2C%22http%3A%2F%2Fschema.org%2Fname%22%3A%5B%7B%22%40value%22%3A%22Vertical%20Coordinates%22%7D%5D%2C%22http%3A%2F%2Fschema.org%2Fvalue%22%3A%5B%7B%22%40value%22%3A%22NAVD88%20%5BEPSG%3A%205703%5D%22%7D%5D%7D%5D%2C%22http%3A%2F%2Fschema.org%2Fgeo%22%3A%5B%7B%22%40type%22%3A%5B%22http%3A%2F%2Fschema.org%2FGeoShape%22%5D%2C%22http%3A%2F%2Fschema.org%2Fbox%22%3A%5B%7B%22%40value%22%3A%2246.9446036594424%2C-116.455371720924%2047.0716151552612%2C-116.250917377739%22%7D%5D%7D%5D%7D%5D%2C%22http%3A%2F%2Fschema.org%2FtemporalCoverage%22%3A%5B%7B%22%40value%22%3A%222004-07-10%2F2004-07-12%22%7D%5D%2C%22http%3A%2F%2Fschema.org%2Fusageinfo%22%3A%5B%7B%22%40value%22%3A%22https%3A%2F%2Fopentopography.org%2Fusageterms%22%7D%5D%2C%22http%3A%2F%2Fschema.org%2FvariableMeasured%22%3A%5B%7B%22%40type%22%3A%5B%22http%3A%2F%2Fschema.org%2FPropertyValue%22%5D%2C%22http%3A%2F%2Fschema.org%2Fname%22%3A%5B%7B%22%40value%22%3A%22Area%22%7D%5D%2C%22http%3A%2F%2Fschema.org%2Fvalue%22%3A%5B%7B%22%40value%22%3A%22132%20km2%22%7D%5D%7D%2C%7B%22%40type%22%3A%5B%22http%3A%2F%2Fschema.org%2FPropertyValue%22%5D%2C%22http%3A%2F%2Fschema.org%2Fname%22%3A%5B%7B%22%40value%22%3A%22Unit%22%7D%5D%2C%22http%3A%2F%2Fschema.org%2Fvalue%22%3A%5B%7B%22%40value%22%3A%22meter%22%7D%5D%7D%2C%7B%22%40type%22%3A%5B%22http%3A%2F%2Fschema.org%2FPropertyValue%22%5D%2C%22http%3A%2F%2Fschema.org%2Fname%22%3A%5B%7B%22%40value%22%3A%22LidarReturns%22%7D%5D%2C%22http%3A%2F%2Fschema.org%2Fvalue%22%3A%5B%7B%22%40value%22%3A%22139931386%20points%22%7D%5D%7D%2C%7B%22%40type%22%3A%5B%22http%3A%2F%2Fschema.org%2FPropertyValue%22%5D%2C%22http%3A%2F%2Fschema.org%2Fname%22%3A%5B%7B%22%40value%22%3A%22PointDensity%22%7D%5D%2C%22http%3A%2F%2Fschema.org%2Fvalue%22%3A%5B%7B%22%40value%22%3A%221.06%20points%2Fm2%22%7D%5D%7D%5D%2C%22http%3A%2F%2Fschema.org%2Fversion%22%3A%5B%7B%22%40value%22%3A%221.0%22%7D%5D%7D&frame=%7B%22%40context%22%3A%22http%3A%2F%2Fschema.org%2F%22%2C%22%40type%22%3A%22Dataset%22%2C%22identifier%22%3A%7B%7D%2C%22creator%22%3A%7B%7D%7D) and not software.

**Comment by iannesbitt** [comment]
Probably shouldn't be used but here's the code change that would allow scraping `@id` in addition to `@value`:
```diff
def _getIdentifiers(doc):
    ids = []
    v = doc.get("@value", None)
    if not v is None:
        ids.append(v)
        return ids
    vs = doc.get(sonormal.SO_VALUE, [])
    for av in vs:
        v = av.get("@value", None)
        if v is not None:
            ids.append(v)
+   v = doc.get("@id", None)
+   if not v is None:
+       ids.append(v)
+       return ids
    return ids
```

**Comment by iannesbitt** [comment]
Got the ok from @rushirajnenuji to make this change as `@id` can replace other values in the `identifier` field during framing.

**Comment by iannesbitt** [comment]
Closing as fixed.

**Comment by mbjones** [comment]
> Got the ok from @rushirajnenuji to make this change as @id can replace other values in the identifier field during framing.

@iannesbitt we should discuss the implications of this change before you finalize it please. Let's discuss during our dev meeting on Thursday.

**Comment by iannesbitt** [comment]
Ok. I still have some questions about it as well. Thank you for catching this.

**Comment by iannesbitt** [comment]
This issue has been determined to stem from the use of dual `@id` tags in the JSON-LD document. It seems that framing gets rid of other fields in the `identifier` when `@id` exists within it.

Framing example [with](https://tinyurl.com/wa2wa4r4) and [without](https://tinyurl.com/4szfmhvr) `identifier` > `@id`.

Instead of a code change, I will contact OpenTopography directly. See DataONEorg/member-repos#15
